name: INFRA WORKFLOW AKS #optional pipeline name

on:  #workflow kab chalega
  push:
    branches:
    - main
    - feature/*
permissions:  #OIDC m permission dena padta h
  id-token: write
  contents: read
  
jobs:
  scanning_tool:
    name: scanning tool
    runs-on: ubuntu-latest # y github hosted m run hoga
    steps:
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v6.2.1  
    - name: Run TFLint
      run: tflint -f compact --recursive
     
  
    
  terraform_init_plan:  #job id
    name: terraform init plan #job name
    runs-on: self-hosted #runner and tag dena padta h
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: 4b3d71c1-b88b-425b-b0ee-1870ba610fe2
        # TenantId of the Azure Service principal created.
        tenant-id: d1eccdf5-b342-4b78-ab32-7f11700de7e4
        subscription-id: 09250277-3461-4a76-b62f-8499b8d4c172
    
    - name: terraform fmt
      run: terraform fmt
      working-directory: env/dev
      
    - name: terraforminit
      run: terraform init
      working-directory: env/dev
      
    - name: terraform plan
      run: terraform plan
      working-directory: env/dev

      
  terraform_init_apply:  #job id
    name: terraform appply plan #job name
    runs-on: self-hosted #runner and tag dena padta h
    needs: terraform_init_plan # y depends_on ki trah h
    environment: dev # y approval k liye h
    
    steps:
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: 4b3d71c1-b88b-425b-b0ee-1870ba610fe2
        # TenantId of the Azure Service principal created.
        tenant-id: d1eccdf5-b342-4b78-ab32-7f11700de7e4
        subscription-id: 09250277-3461-4a76-b62f-8499b8d4c172
    
    - name: terraform init
      run: terraform init
      working-directory: env/dev
      
    - name: terraform apply
      if: github.ref == 'refs/heads/main' # sirf main s chlega apply y condition h 
      run: terraform apply --auto-approve
      working-directory: env/dev

